### ISSUE TITLE
Problems with the new validation package on AIX.

### ISSUE THREAD

**Issue by Tpendrup** [oriol/validation-tools#10]
Hello
We have tried to run the new 3.1 PEPPOL schematrons on our system (AIX 5.3 wpar on 7.1 lpar). We found a problem in "BIIRULES-UBL-T10.xsl" that fails on this rule:
"[BII2-T10-R058]-Invoice total without VAT MUST be equal to the sum of VAT category taxable amounts; "
When we run the same validation on the same document on Windows and Linux we get no errors.
We have tried different versions of Saxon9 and Java on all environments with the same result:
- Ok on Linux and Windows,
- Not OK on AIX.

Does anybody have any idea about what the problem might be.

You can find the testfile here:
https://joinup.ec.europa.eu/community/pid/topic/problems-new-validation-package-aix

**Comment by phax** [comment]
Copy from the other forum:

> Yes. It is the assert that are failing as if there actual where a calculation error.
> 
> But it as a very simple example with only one TaxSubtotal group.
> 
> BII2-T10-R058; [flag]=fatal; [Description]=[BII2-T10-R058]-Invoice total without VAT MUST be equal to the sum of VAT category taxable amounts; [test]=((cac:TaxTotal[cac:TaxSubtotal/cac:TaxCategory/cac:TaxScheme/cbc:ID = 'VAT']/cbc:TaxAmount) and (round(xs:decimal(sum(cac:TaxTotal//cac:TaxSubtotal/cbc:TaxableAmount)) *10 \* 10) div 100 = (xs:decimal(cac:LegalMonetaryTotal/cbc:TaxExclusiveAmount)

**Comment by oriol** [comment]
Can you provide me with some samples where this rule is not working?

**Comment by Tpendrup** [comment]
Hello.

Try this example.
As I wrote it validates OK on windows and linux.
But it fails in our AIX environments.

/thomas

**Comment by oriol** [comment]
This instance only fires a warning in the environments I have. Cannot test in AIX though.

**Comment by phax** [comment]
@Tpendrup Can you elaborate a bit on the XSLT library that you are using on AIX. Thanks

**Comment by Tpendrup** [comment]
On AIX we have tried "Saxon9-9.2.1.5" and "SaxonHE9-6-0-7J" . 
Both versions works fine on Linux and Windows.

**Comment by Tpendrup** [comment]
I have left a note with MySupply in Denmark - to see if they have an AIX system we can use to verify the problem.

**Comment by phax** [comment]
I potentially has something to do with the IBM JDK used on AIX compared to the Oracle JDK...

**Comment by Tpendrup** [comment]
Good news.
The issue is solved by updating our 2009 JAVA.6 (IBM jre) with the latest fixes,.
Thank you all.

**Comment by oriol** [comment]
Thank you for your comments!
