### ISSUE TITLE
OpenPEPPOL CodeList CVA reference is invalid

### ISSUE THREAD

**Issue by phax** [oriol/validation-tools#2]
The fields G45 and G49 in the OpenPEPPOL CodeList CVA sheet refers to the non-existing code list "currencyCodeList" but it should be "CurrencyCodeList".

Thanks

**Comment by oriol** [comment]
Closed cf7f5c314db451dbe703785f94cfcbc21ce9c3dc

**Comment by phax** [comment]
The issue remains for OP-T76-R003

**Comment by oriol** [comment]
Should be corrected now.

**Comment by phax** [comment]
works thanks.
