### ISSUE TITLE
OpenPEPPOL CodeList refers to StandardItemIdentifier but only CommodityCode is present

### ISSUE THREAD

**Issue by phax** [oriol/validation-tools#3]
The OpenPEPPOL CVA sheet refers to the code list `StandardItemIdentifier` for the XPaths `cac:Item/cac:StandardItemIdentification/cbc:ID/@schemeID` and `cac:Item/cac:StandardItemIdentification/cbc:ID` but there is no such sheet in the ODS files.
But instead there is a sheet called `CommodityCode` in the ODS file which seem to match (from my point of view at least for the first one).

So if this is a typo, please either rename the sheet `CommodityCode` to `StandardItemIdentifier` or change the name in the CVA sheet. Thanks.

**Comment by oriol** [comment]
Closed cf7f5c314db451dbe703785f94cfcbc21ce9c3dc
