### ISSUE TITLE
UBL Mapping for BII2-T01-R014 contains an XPath error

### ISSUE THREAD

**Issue by phax** [oriol/validation-tools#6]
The expression `(xs:decimal(cbc:LineExtensionAmount)) = (round(sum((xs:decimal(/ubl:Order/cac:OrderLine/cac:LineItem/cbc:LineExtensionAmount)) * 10 * 10) div 100)` has one opening bracket too much after `sum`. It should be:

`(xs:decimal(cbc:LineExtensionAmount)) = (round(sum(xs:decimal(/ubl:Order/cac:OrderLine/cac:LineItem/cbc:LineExtensionAmount)) * 10 * 10) div 100)`

**Comment by oriol** [comment]
Should be fixed now

**Comment by phax** [comment]
thanks :)
