### ISSUE TITLE
OP-T10-R007 is missing support for "GTIN"

### ISSUE THREAD

**Issue by phax** [oriol/validation-tools#9]
E.g. example file Use Case 2_ExampleFile_PEPPOL BIS.xml is using the scheme "GTIN" in

`InvoiceLine[ID="2"]/cac:Item/cac:StandardItemIdentification/cbc:ID/@schemeID`

Is it a bug in the examples or is the scheme "GTIN" missing in the OpenPEPPOL codelist for `CommodityCode`??

**Comment by oriol** [comment]
I think we should raise that issue to OpenPEPPOL. Maybe the original error was the need for an specific standard item identification different from the commodity code.

**Comment by phax** [comment]
Sounds like a plan - can you do it please? Thanks

**Comment by oriol** [comment]
Resolved in f4e42b1efec544ca626ac332ecb2d2a58bbeff51 after resolution from CMB to remove rules OP-T10-R007 and OP-T14-R007
